name: Selenium Test

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  selenium-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Download latest ChromeDriver
        run: |
          mkdir -p ~/drivers/chromedriver
          LATEST=$(curl -sSL https://chromedriver.storage.googleapis.com/LATEST_RELEASE)
          wget https://chromedriver.storage.googleapis.com/${LATEST}/chromedriver_linux64.zip -O chromedriver.zip
          unzip chromedriver.zip -d ~/drivers/chromedriver
          chmod +x ~/drivers/chromedriver/chromedriver
          echo "$HOME/drivers/chromedriver" >> $GITHUB_PATH

      - name: Run Selenium script
        run: |
          python script.py
