name: Selenium Test with WebDriverManager

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  selenium-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Cache pip packages
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Cache WebDriverManager binaries
        uses: actions/cache@v4
        with:
          path: ~/.wdm
          key: wdm-${{ runner.os }}
          restore-keys: |
            wdm-

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Selenium test
        run: |
          python script.py
